local M = {}

function M.setup(c)
  local hl = function(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
  end

  -- editor
  hl("Normal", { fg = c.fg, bg = c.bg })
  hl("NormalFloat", { fg = c.fg, bg = c.bg_elevated })
  hl("FloatBorder", { fg = c.border, bg = c.bg_elevated })
  hl("FloatTitle", { fg = c.accent, bg = c.bg_elevated })
  hl("Cursor", { fg = c.bg, bg = c.accent })
  hl("CursorLine", { bg = c.bg })
  hl("CursorLineNr", { fg = c.fg })
  hl("LineNr", { fg = c.line_nr })
  hl("SignColumn", { bg = c.bg })
  hl("VertSplit", { fg = c.border })
  hl("WinSeparator", { fg = c.border })
  hl("StatusLine", { fg = c.fg_muted, bg = c.bg })
  hl("StatusLineNC", { fg = c.fg_dim, bg = c.bg })
  hl("TabLine", { fg = c.fg_muted, bg = c.bg })
  hl("TabLineFill", { bg = c.bg })
  hl("TabLineSel", { fg = c.fg, bg = c.bg_elevated })
  hl("Pmenu", { fg = c.fg, bg = c.bg_elevated })
  hl("PmenuSel", { fg = c.fg, bg = c.bg_selected })
  hl("PmenuSbar", { bg = c.bg_elevated })
  hl("PmenuThumb", { bg = c.bg_hover })
  hl("Visual", { bg = c.bg_hover })
  hl("Search", { fg = c.fg, bg = c.search })
  hl("IncSearch", { fg = c.bg, bg = c.accent })
  hl("CurSearch", { fg = c.bg, bg = c.accent })
  hl("MatchParen", { fg = c.accent, bg = c.bg_hover })
  hl("Folded", { fg = c.fg_muted, bg = c.bg_elevated })
  hl("FoldColumn", { fg = c.fg_dim, bg = c.bg })
  hl("NonText", { fg = c.fg_dim })
  hl("SpecialKey", { fg = c.fg_dim })
  hl("Whitespace", { fg = c.fg_dim })
  hl("EndOfBuffer", { fg = c.bg })
  hl("Directory", { fg = c.string })
  hl("Question", { fg = c.accent })
  hl("MoreMsg", { fg = c.accent })
  hl("ModeMsg", { fg = c.fg_muted })
  hl("ErrorMsg", { fg = c.error })
  hl("WarningMsg", { fg = c.warning })
  hl("Title", { fg = c.accent })
  hl("WildMenu", { fg = c.fg, bg = c.bg_selected })

  -- syntax
  hl("Comment", { fg = c.comment })
  hl("Constant", { fg = c.accent })
  hl("String", { fg = c.string })
  hl("Character", { fg = c.string })
  hl("Number", { fg = c.accent })
  hl("Boolean", { fg = c.accent })
  hl("Float", { fg = c.accent })
  hl("Identifier", { fg = c.fg })
  hl("Function", { fg = c.accent })
  hl("Statement", { fg = c.fg_muted })
  hl("Conditional", { fg = c.fg_muted })
  hl("Repeat", { fg = c.fg_muted })
  hl("Label", { fg = c.accent })
  hl("Operator", { fg = c.fg_muted })
  hl("Keyword", { fg = c.fg_muted })
  hl("Exception", { fg = c.fg_muted })
  hl("PreProc", { fg = c.fg_muted })
  hl("Include", { fg = c.fg_muted })
  hl("Define", { fg = c.fg_muted })
  hl("Macro", { fg = c.accent })
  hl("PreCondit", { fg = c.fg_muted })
  hl("Type", { fg = c.accent })
  hl("StorageClass", { fg = c.fg_muted })
  hl("Structure", { fg = c.accent })
  hl("Typedef", { fg = c.accent })
  hl("Special", { fg = c.accent })
  hl("SpecialChar", { fg = c.accent })
  hl("Tag", { fg = c.accent })
  hl("Delimiter", { fg = c.fg_muted })
  hl("SpecialComment", { fg = c.comment })
  hl("Debug", { fg = c.error })
  hl("Underlined", { fg = c.accent, underline = true })
  hl("Error", { fg = c.error })
  hl("Todo", { fg = c.accent, bg = c.bg_elevated })

  -- diagnostics
  hl("DiagnosticError", { fg = c.error })
  hl("DiagnosticWarn", { fg = c.warning })
  hl("DiagnosticInfo", { fg = c.info })
  hl("DiagnosticHint", { fg = c.hint })
  hl("DiagnosticUnderlineError", { sp = c.error, undercurl = true })
  hl("DiagnosticUnderlineWarn", { sp = c.warning, undercurl = true })
  hl("DiagnosticUnderlineInfo", { sp = c.info, undercurl = true })
  hl("DiagnosticUnderlineHint", { sp = c.hint, undercurl = true })
  hl("DiagnosticVirtualTextError", { fg = c.error, bg = c.bg })
  hl("DiagnosticVirtualTextWarn", { fg = c.warning, bg = c.bg })
  hl("DiagnosticVirtualTextInfo", { fg = c.info, bg = c.bg })
  hl("DiagnosticVirtualTextHint", { fg = c.hint, bg = c.bg })
  hl("DiagnosticFloatingError", { fg = c.error })
  hl("DiagnosticFloatingWarn", { fg = c.warning })
  hl("DiagnosticFloatingInfo", { fg = c.info })
  hl("DiagnosticFloatingHint", { fg = c.hint })
  hl("DiagnosticSignError", { fg = c.error })
  hl("DiagnosticSignWarn", { fg = c.warning })
  hl("DiagnosticSignInfo", { fg = c.info })
  hl("DiagnosticSignHint", { fg = c.hint })

  -- lsp
  hl("LspReferenceText", { bg = c.bg_hover })
  hl("LspReferenceRead", { bg = c.bg_hover })
  hl("LspReferenceWrite", { bg = c.bg_hover })
  hl("LspSignatureActiveParameter", { fg = c.accent })
  hl("LspInlayHint", { fg = c.fg_dim, bg = c.bg })

  -- diff
  hl("DiffAdd", { fg = c.added, bg = c.bg })
  hl("DiffChange", { fg = c.changed, bg = c.bg })
  hl("DiffDelete", { fg = c.deleted, bg = c.bg })
  hl("DiffText", { fg = c.changed, bg = c.bg_hover })
  hl("Added", { fg = c.added })
  hl("Changed", { fg = c.changed })
  hl("Removed", { fg = c.deleted })

  -- gitsigns
  hl("GitSignsAdd", { fg = c.added })
  hl("GitSignsChange", { fg = c.changed })
  hl("GitSignsDelete", { fg = c.deleted })

  -- mini.diff
  hl("MiniDiffSignAdd", { fg = c.added })
  hl("MiniDiffSignChange", { fg = c.changed })
  hl("MiniDiffSignDelete", { fg = c.deleted })
  hl("MiniDiffOverAdd", { fg = c.added, bg = c.bg })
  hl("MiniDiffOverChange", { fg = c.changed, bg = c.bg })
  hl("MiniDiffOverDelete", { fg = c.deleted, bg = c.bg })

  -- mini.statusline
  hl("MiniStatuslineDevinfo", { fg = c.fg_muted, bg = c.bg })
  hl("MiniStatuslineFileinfo", { fg = c.fg_muted, bg = c.bg })
  hl("MiniStatuslineFilename", { fg = c.fg, bg = c.bg })
  hl("MiniStatuslineInactive", { fg = c.fg_dim, bg = c.bg })
  hl("MiniStatuslineModeCommand", { fg = c.bg, bg = c.accent })
  hl("MiniStatuslineModeInsert", { fg = c.bg, bg = c.accent })
  hl("MiniStatuslineModeNormal", { fg = c.bg, bg = c.fg_muted })
  hl("MiniStatuslineModeOther", { fg = c.bg, bg = c.fg_dim })
  hl("MiniStatuslineModeReplace", { fg = c.bg, bg = c.fg_muted })
  hl("MiniStatuslineModeVisual", { fg = c.bg, bg = c.accent })

  -- telescope
  hl("TelescopeNormal", { fg = c.fg, bg = c.bg })
  hl("TelescopeBorder", { fg = c.border, bg = c.bg })
  hl("TelescopeTitle", { fg = c.accent, bg = c.bg })
  hl("TelescopePromptNormal", { fg = c.fg, bg = c.bg })
  hl("TelescopePromptBorder", { fg = c.border, bg = c.bg })
  hl("TelescopePromptTitle", { fg = c.accent, bg = c.bg })
  hl("TelescopePromptPrefix", { fg = c.accent, bg = c.bg })
  hl("TelescopeResultsNormal", { fg = c.fg, bg = c.bg })
  hl("TelescopeResultsBorder", { fg = c.border, bg = c.bg })
  hl("TelescopeResultsTitle", { fg = c.accent, bg = c.bg })
  hl("TelescopePreviewNormal", { fg = c.fg, bg = c.bg })
  hl("TelescopePreviewBorder", { fg = c.border, bg = c.bg })
  hl("TelescopePreviewTitle", { fg = c.accent, bg = c.bg })
  hl("TelescopeSelection", { fg = c.fg, bg = c.bg_selected })
  hl("TelescopeSelectionCaret", { fg = c.accent, bg = c.bg_selected })
  hl("TelescopeMatching", { fg = c.accent })

  -- blink.cmp
  hl("BlinkCmpMenu", { fg = c.fg, bg = c.bg_elevated })
  hl("BlinkCmpMenuBorder", { fg = c.border, bg = c.bg_elevated })
  hl("BlinkCmpMenuSelection", { bg = c.bg_selected })
  hl("BlinkCmpLabel", { fg = c.fg })
  hl("BlinkCmpLabelMatch", { fg = c.accent })
  hl("BlinkCmpLabelDescription", { fg = c.fg_muted })
  hl("BlinkCmpKind", { fg = c.accent })
  hl("BlinkCmpDoc", { fg = c.fg, bg = c.bg_elevated })
  hl("BlinkCmpDocBorder", { fg = c.border, bg = c.bg_elevated })
  hl("BlinkCmpSignatureHelp", { fg = c.fg, bg = c.bg_elevated })
  hl("BlinkCmpSignatureHelpBorder", { fg = c.border, bg = c.bg_elevated })

  -- oil
  hl("OilDir", { fg = c.string })
  hl("OilFile", { fg = c.fg })
  hl("OilSocket", { fg = c.fg_muted })
  hl("OilLink", { fg = c.string })
  hl("OilLinkTarget", { fg = c.fg_muted })

  -- treesitter
  hl("@variable", { fg = c.fg })
  hl("@variable.builtin", { fg = c.fg_muted })
  hl("@variable.parameter", { fg = c.fg })
  hl("@variable.member", { fg = c.fg })
  hl("@constant", { fg = c.accent })
  hl("@constant.builtin", { fg = c.accent })
  hl("@constant.macro", { fg = c.accent })
  hl("@module", { fg = c.fg })
  hl("@label", { fg = c.accent })
  hl("@string", { fg = c.string })
  hl("@string.escape", { fg = c.accent })
  hl("@string.regexp", { fg = c.string })
  hl("@string.special", { fg = c.string })
  hl("@character", { fg = c.string })
  hl("@character.special", { fg = c.accent })
  hl("@boolean", { fg = c.accent })
  hl("@number", { fg = c.accent })
  hl("@number.float", { fg = c.accent })
  hl("@type", { fg = c.accent })
  hl("@type.builtin", { fg = c.accent })
  hl("@type.definition", { fg = c.accent })
  hl("@attribute", { fg = c.fg_muted })
  hl("@property", { fg = c.fg })
  hl("@function", { fg = c.accent })
  hl("@function.builtin", { fg = c.accent })
  hl("@function.macro", { fg = c.accent })
  hl("@function.method", { fg = c.accent })
  hl("@constructor", { fg = c.accent })
  hl("@operator", { fg = c.fg_muted })
  hl("@keyword", { fg = c.fg_muted })
  hl("@keyword.modifier", { fg = c.fg_muted })
  hl("@keyword.type", { fg = c.fg_muted })
  hl("@keyword.coroutine", { fg = c.fg_muted })
  hl("@keyword.function", { fg = c.fg_muted })
  hl("@keyword.operator", { fg = c.fg_muted })
  hl("@keyword.import", { fg = c.fg_muted })
  hl("@keyword.repeat", { fg = c.fg_muted })
  hl("@keyword.return", { fg = c.fg_muted })
  hl("@keyword.exception", { fg = c.fg_muted })
  hl("@keyword.conditional", { fg = c.fg_muted })
  hl("@punctuation", { fg = c.fg_muted })
  hl("@punctuation.delimiter", { fg = c.fg_muted })
  hl("@punctuation.bracket", { fg = c.fg_muted })
  hl("@punctuation.special", { fg = c.fg_muted })
  hl("@comment", { fg = c.comment })
  hl("@comment.documentation", { fg = c.comment })
  hl("@comment.error", { fg = c.error })
  hl("@comment.warning", { fg = c.warning })
  hl("@comment.todo", { fg = c.accent })
  hl("@comment.note", { fg = c.info })
  hl("@markup.heading", { fg = c.accent })
  hl("@markup.quote", { fg = c.fg_muted })
  hl("@markup.math", { fg = c.accent })
  hl("@markup.link", { fg = c.accent })
  hl("@markup.link.label", { fg = c.accent })
  hl("@markup.link.url", { fg = c.string, underline = true })
  hl("@markup.raw", { fg = c.string })
  hl("@markup.list", { fg = c.fg_muted })
  hl("@markup.strong", { bold = true })
  hl("@markup.italic", { italic = true })
  hl("@markup.strikethrough", { strikethrough = true })
  hl("@tag", { fg = c.accent })
  hl("@tag.attribute", { fg = c.fg_muted })
  hl("@tag.delimiter", { fg = c.fg_muted })

  -- flash.nvim
  hl("FlashLabel", { fg = c.bg, bg = c.accent, bold = true })
  hl("FlashMatch", { fg = c.accent })
  hl("FlashCurrent", { fg = c.bg, bg = c.string })
  hl("FlashBackdrop", { fg = c.comment })

  -- terminal colors
  vim.g.terminal_color_0 = c.bg
  vim.g.terminal_color_1 = c.error
  vim.g.terminal_color_2 = c.string
  vim.g.terminal_color_3 = c.accent
  vim.g.terminal_color_4 = c.fg_muted
  vim.g.terminal_color_5 = c.accent
  vim.g.terminal_color_6 = c.string
  vim.g.terminal_color_7 = c.fg
  vim.g.terminal_color_8 = c.line_nr
  vim.g.terminal_color_9 = c.error_bright
  vim.g.terminal_color_10 = c.string_bright
  vim.g.terminal_color_11 = c.accent_bright
  vim.g.terminal_color_12 = c.fg_muted_bright
  vim.g.terminal_color_13 = c.accent
  vim.g.terminal_color_14 = c.string_dim
  vim.g.terminal_color_15 = c.fg
end

return M
